-
  name: Playbook to setup apache Server

  hosts: controlnode
  become: True
  tasks:
    - name: Install Apache package
      yum:
        name: httpd
        state: present
        use_backend: "yum"
    - name: Modifying the contents of index.html page
      copy:
        dest: "/var/www/html/index.html"
        content: "<h1>This is a Webpage created using Ansible on Jenkins</h1>"

    - name: Allow the port in firewall
      firewalld:
        zone: public
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Start the Apache service
      systemd:
        name: httpd
        state: started
        enabled: true
        
    
