-
  name: Playbook to setup apache Server

  hosts: vm
  become: True
  tasks:
    - name: Install Apache package
      apt:
        name: apache2
        state: present
       
    - name: Modifying the contents of index.html page
      copy:
        dest: "/var/www/html/index.html"
        content: "<h1>This is a Webpage created using Ansible</h1>"

    - name: Allow the port in firewall
      firewalld:
        zone: public
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Start the Apache service
      systemd:
        name: apache2
        state: started
        enabled: true
        
    
